// Generated by CoffeeScript 1.6.3
// except getCssSelectorOF, getElementId and getPathTo handmade customizations
// The code for getCssSelectorOF was partially borrowed from chromium project:
// https://chromium.googlesource.com/chromium/src.git


(function () {
    var Automation_Page_Recorder, addStyle, bye, createCommand, dbg, getInputElementsByTypeAndValue, getPageXY, getCssSelectorOF, getElementId, getPathTo, handler, hello, prev, preventEvent, pseudoGuid, rightClickHandler, say;
    var commandSent = false;
    var ELEMENT_NODE = 1;

    say = function (something) {
        if (typeof console !== "undefined" && console !== null) {
            return console.log(something);
        }
    };

    dbg = function (something) {
        if (typeof console !== "undefined" && console !== null) {
            return console.log("DBG:" + something);
        }
    };

    hello = function (something) {
        return dbg("(begin): " + something);
    };

    bye = function (something) {
        return dbg("(end): " + something);
    };

    pseudoGuid = function () {
        var result;
        hello("pseudoGuid");
        result = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx';
        result = result.replace(/[xy]/g, function (re_match) {
            var random_value, replacement;
            random_value = Math.random() * 16 | 0;
            replacement = re_match === 'x' ? random_value : random_value & 0x3 | 0x8;
            return replacement.toString(16);
        });
        bye("pseudoGuid");
        return result;
    };

    function showNotification(message) {
        var notification = document.createElement('div');
        notification.className = 'locator-notification';
        notification.style.position = 'fixed';
        notification.style.top = '50px';
        notification.style.right = '10px';
        notification.style.backgroundColor = '#4CAF50';
        notification.style.color = 'white';
        notification.style.padding = '12px 20px';
        notification.style.borderRadius = '6px';
        notification.style.zIndex = '999999';
        notification.style.fontFamily = 'Arial, sans-serif';
        notification.style.boxShadow = '0 4px 12px rgba(0,0,0,0.2)';
        notification.style.fontWeight = 'bold';
        notification.textContent = message;

        document.body.appendChild(notification);

        setTimeout(function () {
            if (notification.parentNode) {
                document.body.removeChild(notification);
            }
        }, 3000);
    }

    getInputElementsByTypeAndValue = function (inputType, inputValue) {
        var allDocumentInputElements, inputElement, result, _i, _len;
        hello("getInputElementsByTypeAndValue");
        allDocumentInputElements = document.getElementsByTagName('input');
        result = new Array();
        for (_i = 0, _len = allDocumentInputElements.length; _i < _len; _i++) {
            inputElement = allDocumentInputElements[_i];
            if (inputElement.type === inputType && inputElement.value === inputValue) {
                result.push(inputElement);
            }
        }
        bye("getInputElementsByTypeAndValue");
        return result;
    };

    getElementId = function (element) {
        var selector = '';
        hello('getElementId');

        if (element instanceof Element && element.nodeType === ELEMENT_NODE && element.id) {
            selector = element.id;
        }
        bye('getElementId');
        return selector;
    };

    getCssSelectorOF = function (element) {
        hello('getCssSelectorOF');
        if (!(element instanceof Element))
            return '';
        var path = [];
        while (element.nodeType === ELEMENT_NODE) {
            var selector = element.nodeName.toLowerCase();
            if (element.id) {
                if (element.id.indexOf('-') > -1) {
                    selector += '[id = "' + element.id + '"]';
                } else {
                    selector += '#' + element.id;
                }
                path.unshift(selector);
                break;
            } else {
                var element_sibling = element;
                var sibling_cnt = 1;
                while (element_sibling = element_sibling.previousElementSibling) {
                    if (element_sibling.nodeName.toLowerCase() == selector)
                        sibling_cnt++;
                }
                if (sibling_cnt != 1)
                    selector += ':nth-of-type(' + sibling_cnt + ')';
            }
            path.unshift(selector);
            element = element.parentNode;
        }
        bye('getCssSelectorOF');
        return path.join(' > ');
    };

    getPathTo = function (element) {
        hello("getPathTo");
        let tagName = element.tagName.toLowerCase();
        let attributes = [];

        if (element.id) {
            attributes.push(`@id='${element.id}'`);
        }
        else if (element.name) {
            attributes.push(`@name='${element.name}'`);
        }
        else if (element.type && (tagName === 'input' || tagName === 'button')) {
            attributes.push(`@type='${element.type}'`);
        }
        else if (element.className && typeof element.className === 'string') {
            let classList = element.className.trim().split(/\s+/).slice(0, 2).join(' ');
            if (classList) {
                attributes.push(`contains(@class, '${classList}')`);
            }
        }

        if (element.textContent) {
            let text = element.textContent.trim();
            if (text.length > 0 && text.length < 30 &&
                tagName !== 'body' && tagName !== 'html' &&
                !text.includes('\n')) {
                attributes.push(`text()='${text}'`);
            }
        }

        let attributeString = attributes.length ? `[${attributes.join(' and ')}]` : '';
        let xpath = `//${tagName}${attributeString}`;

        bye("getPathTo");
        return xpath;
    }

    getPageXY = function (element) {
        var x, y;
        hello("getPageXY");
        x = 0;
        y = 0;
        while (element) {
            x += element.offsetLeft;
            y += element.offsetTop;
            element = element.offsetParent;
        }
        bye("getPageXY");
        return [x, y];
    };

    createCommand = function (command) {
        if (!Array.isArray(document.Automationpr_command)) {
            document.Automationpr_command = [];
        }
        document.Automationpr_command.push(command);
    };

    addStyle = function (css) {
        var head, style;
        hello("addStyle");
        head = document.getElementsByTagName('head')[0];
        style = document.createElement('style');
        style.type = 'text/css';
        if (style.styleSheet) {
            style.styleSheet.cssText = css;
        } else {
            style.appendChild(document.createTextNode(css));
        }
        head.appendChild(style);
        return bye("addStyle");
    };

    preventEvent = function (event) {
        hello("preventEvent");
        if (event.preventDefault) {
            event.preventDefault();
        }
        event.returnValue = false;
        if (event.stopPropagation) {
            event.stopPropagation();
        } else {
            event.cancelBubble = true;
        }
        bye("preventEvent");
        return false;
    };

    prev = void 0;
    document.Automation_prevActiveElement = void 0;

    function normalizeTarget(el) {
        if (!el || el === document.body)
            return el;

        if (el.tagName && el.tagName.toLowerCase() === 'path' && el.parentElement)
            el = el.parentElement;

        let tag = el.tagName ? el.tagName.toLowerCase() : '';
        if (tag === 'input' || tag === 'textarea' || tag === 'select') {
            return el;
        }

        while (el && el.tagName) {
            let currentTag = el.tagName.toLowerCase();
            if (currentTag === 'button' || currentTag === 'a' ||
                currentTag === 'div' || currentTag === 'input' ||
                currentTag === 'textarea' || currentTag === 'select')
                break;
            el = el.parentElement;
        }

        return el;
    }

    handler = function (event) {
        hello("handler");
        if (document.Automation_Page_Recorder == null) {
            return;
        }
        if (prev) {
            prev.className = prev.className.replace(/\s?\bhighlight\b/, '');
            prev = void 0;
        }
        if (event.ctrlKey) {
            let rawTarget = event.composedPath ? event.composedPath()[0] : event.target;
            let normalized = normalizeTarget(rawTarget);

            if (normalized) {
                prev = normalized;
                prev.className += " highlight";
            }
        }
        return bye("handler");
    };

    rightClickHandler = function (event) {
        var JsonData, body, eventPreventingResult, mxy, path, root, target, txy, xpath, css_selector, id;
        hello("rightClickHandler");
        if (document.Automation_Page_Recorder == null) {
            return;
        }
        if (event.ctrlKey) {
            if (event == null) {
                event = window.event;
            }
            let rawTarget = event.composedPath ? event.composedPath()[0] : event.target;
            target = normalizeTarget(rawTarget);
            root = document.compatMode === 'CSS1Compat' ? document.documentElement : document.body;
            mxy = [event.clientX + root.scrollLeft, event.clientY + root.scrollTop];
            path = getPathTo(target);
            txy = getPageXY(target);
            css_selector = getCssSelectorOF(target);
            id = getElementId(target);
            body = document.getElementsByTagName('body')[0];
            xpath = path;

            console.log('[ElementSearch] Elemento capturado:');
            console.log('ID:', id);
            console.log('CSS:', css_selector);
            console.log('XPath:', xpath);

            JsonData = {
                "Command": "GetXPathFromElement",
                "Caller": "EventListener : mousedown",
                "CommandId": pseudoGuid(),
                "CssSelector": css_selector,
                "ElementId": id,
                "XPathValue": xpath
            };
            createCommand(JsonData);
            document.Automation_Page_Recorder.showPos(event, xpath, css_selector, id);
            eventPreventingResult = preventEvent(event);
            bye("rightClickHandler");
            return eventPreventingResult;
        }
    };

    Automation_Page_Recorder = (function () {
        function Automation_Page_Recorder() { }

        Automation_Page_Recorder.prototype.getMainWinElement = function () {
            return document.getElementById('AutomationPR_PopUp');
        };

        Automation_Page_Recorder.prototype.displayAutomationForm = function (x, y) {
            var el;
            hello("displayAutomationForm");
            el = this.getMainWinElement();

            el.style.background = "white";
            el.style.position = "absolute";
            el.style.left = x + "px";
            el.style.top = y + "px";
            el.style.display = "block";
            el.style.border = "3px solid black";
            el.style.padding = "5px 5px 5px 5px";
            el.style.zIndex = 2147483647;
            el.style.borderRadius = "8px";
            el.style.boxShadow = "0 4px 6px rgba(0,0,0,0.2)";
            el.style.cursor = "move";

            var isDragging = false;
            var offsetX, offsetY;

            if (el._mouseDownHandler) {
                el.removeEventListener('mousedown', el._mouseDownHandler);
            }
            if (el._mouseMoveHandler) {
                document.removeEventListener('mousemove', el._mouseMoveHandler);
            }
            if (el._mouseUpHandler) {
                document.removeEventListener('mouseup', el._mouseUpHandler);
            }

            el._mouseDownHandler = function (e) {
                if (e.target.id === 'AutomationPR_PopUp_CloseButton') return;
                if (e.target.tagName === 'INPUT' || e.target.tagName === 'SELECT' || e.target.tagName === 'BUTTON') return;

                isDragging = true;
                offsetX = e.clientX - el.offsetLeft;
                offsetY = e.clientY - el.offsetTop;
                el.style.cursor = "grabbing";
                e.preventDefault();
            };

            el._mouseMoveHandler = function (e) {
                if (isDragging) {
                    e.preventDefault();
                    var newX = e.clientX - offsetX;
                    var newY = e.clientY - offsetY;

                    newX = Math.max(0, Math.min(newX, window.innerWidth - el.offsetWidth));
                    newY = Math.max(0, Math.min(newY, window.innerHeight - el.offsetHeight));

                    el.style.left = newX + "px";
                    el.style.top = newY + "px";
                }
            };

            el._mouseUpHandler = function () {
                if (isDragging) {
                    isDragging = false;
                    el.style.cursor = "move";
                }
            };

            el.addEventListener('mousedown', el._mouseDownHandler);
            document.addEventListener('mousemove', el._mouseMoveHandler);
            document.addEventListener('mouseup', el._mouseUpHandler);

            return bye("displayAutomationForm");
        };

        Automation_Page_Recorder.prototype.showPos = function (event, xpath, css_selector, id) {
            var x, y;
            hello("showPos");
            if (window.event) {
                x = window.event.clientX + document.documentElement.scrollLeft + document.body.scrollLeft;
                y = window.event.clientY + document.documentElement.scrollTop + document.body.scrollTop;
            } else {
                x = event.clientX + window.scrollX;
                y = event.clientY + window.scrollY;
            }
            x -= 2;
            y -= 2;
            y = y + 15;
            this.displayAutomationForm(x, y);

            console.log('[showPos] Nova captura recebida:');
            console.log('ID:', id);
            console.log('CSS:', css_selector);
            console.log('XPath:', xpath);

            var idElement = document.getElementById("AutomationPR_PopUp_ElementId");
            var xpathElement = document.getElementById("AutomationPR_PopUp_XPathLocator");
            var cssElement = document.getElementById("AutomationPR_PopUp_CssSelector");

            idElement.setAttribute('data-value', id || '');
            xpathElement.setAttribute('data-value', xpath || '');
            cssElement.setAttribute('data-value', css_selector || '');

            idElement.textContent = id || '(vazio)';
            xpathElement.textContent = xpath || '(vazio)';
            cssElement.textContent = css_selector || '(vazio)';

            document.getElementById("AutomationPR_PopUp_CodeIDText").value = '';
            document.getElementById("AutomationPR_PopUp_CodeIDText").focus();

            this.populateFeatureDropdown();

            var radioId = document.getElementById("chkId");
            var radioXpath = document.getElementById("chkXpath");
            var radioCss = document.getElementById("chkCss");

            if (id && id !== '') {
                radioId.checked = true;
                radioXpath.checked = false;
                radioCss.checked = false;
                console.log('[showPos] Radio ID selecionado');
            } else {
                radioId.checked = false;
                radioXpath.checked = true;
                radioCss.checked = false;
                console.log('[showPos] Radio XPath selecionado');
            }

            var insertBtn = document.getElementById("AutomationPR_InsertButton");
            if (insertBtn) {
                insertBtn.style.display = 'none';
            }

            say(x + ";" + y);
            return bye("showPos");
        };

        Automation_Page_Recorder.prototype.populateFeatureDropdown = function () {
            console.log('[populateFeatureDropdown] Iniciando...');
            console.log('[populateFeatureDropdown] window.availableFeatures:', window.availableFeatures);

            var dropdown = document.getElementById("AutomationPR_FeatureSelect");
            dropdown.innerHTML = '';

            var defaultOption = document.createElement('option');
            defaultOption.value = '';
            defaultOption.text = 'Selecione uma Feature...';
            dropdown.appendChild(defaultOption);

            if (window.availableFeatures && Array.isArray(window.availableFeatures) && window.availableFeatures.length > 0) {
                console.log('[populateFeatureDropdown] Total de features:', window.availableFeatures.length);

                window.availableFeatures.forEach(function (feature) {
                    console.log('[populateFeatureDropdown] Adicionando feature:', feature);
                    var option = document.createElement('option');
                    option.value = feature;
                    option.text = feature;
                    dropdown.appendChild(option);
                });
            } else {
                console.log('[populateFeatureDropdown] Nenhuma feature disponível!');
                var noFeatureOption = document.createElement('option');
                noFeatureOption.value = '';
                noFeatureOption.text = '(Nenhum arquivo .feature encontrado)';
                noFeatureOption.disabled = true;
                dropdown.appendChild(noFeatureOption);
            }
        };

        Automation_Page_Recorder.prototype.closeForm = function () {
            return document.getElementById('AutomationPR_PopUp').style.display = 'none';
        };

        Automation_Page_Recorder.prototype.createElementForm = function () {
            var closeClickHandler, element;
            hello("createElementForm");
            element = document.createElement("div");
            element.id = 'AutomationPR_PopUp';
            if (document.body != null) {
                document.body.appendChild(element);
            } else {
                say("createElementForm Failed to inject element AutomationPR_PopUp. The document has no body");
            }
            closeClickHandler = "";
            element.innerHTML = '\
    <table id="AutomationTable">\
        <tr>\
          <td><b>Feature</b></td>\
          <td>\
            <select id="AutomationPR_FeatureSelect" style="width: 100%; max-width: 300px;">\
              <option value="">Selecione...</option>\
            </select>\
          </td>\
        </tr>\
        <tr>\
          <td><b>Nome Elemento</b></td>\
          <td>\
                <div id="AutomationPR_PopUp_Element_Name">\
                    <span id="AutomationPR_PopUp_CodeID">\
                        <input type="text" id="AutomationPR_PopUp_CodeIDText" placeholder="Ex: textboxPesquisa">\
                    </span>\
                 </div>\
          </td>\
        </tr>\
        <tr>\
          <td><b>Element</b></td>\
          <td><span id="AutomationPR_PopUp_ElementName">Element</span></td>\
        </tr>\
        <tr>\
          <td><input type="radio" name="locatorType" id="chkId" value="id"><b>id:</b></td>\
          <td><span id="AutomationPR_PopUp_ElementId" data-value=""></span></td>\
        </tr>\
        <tr>\
          <td><input type="radio" name="locatorType" id="chkXpath" value="xpath" checked><b>xpath:</b></td>\
          <td><span id="AutomationPR_PopUp_XPathLocator" data-value=""></span></td>\
        </tr>\
        <tr>\
          <td><input type="radio" name="locatorType" id="chkCss" value="css"><b>css:</b></td>\
          <td><span id="AutomationPR_PopUp_CssSelector" data-value=""></span></td>\
        </tr>\
        </table>\
    <input type="button" id="AutomationPR_SaveButton" value="Salvar" style="font-weight: bold;" onclick="document.Automation_Page_Recorder.addElement()">\
    <input type="button" id="AutomationPR_InsertButton" value="Inserir no XML" style="font-weight: bold; margin-left: 5px; display: none;" onclick="handleSaveToXml()">\
    <input type="button" value="Fechar" style="font-weight: bold; margin-left: 5px;" onclick="document.Automation_Page_Recorder.closeForm()">\
    ';
            return bye("createElementForm");
        };

        Automation_Page_Recorder.prototype.addElement = function () {
            var JsonData, XPathLocatorElement, codeIDTextElement, htmlIdElement, CssSelectorElement;
            var featureSelect, featureName, elementName, fullElementKey;
            var selectedLocatorType, selectedLocatorValue;

            hello("addElement");

            function decodeHtml(html) {
                var txt = document.createElement("textarea");
                txt.innerHTML = html;
                return txt.value;
            }

            featureSelect = document.getElementById("AutomationPR_FeatureSelect");
            featureName = featureSelect.value.trim();

            console.log('[addElement] Feature selecionada:', featureName);

            if (!featureName) {
                alert('Por favor, selecione uma feature!');
                return;
            }

            codeIDTextElement = document.getElementById("AutomationPR_PopUp_CodeIDText");
            elementName = codeIDTextElement.value.trim();

            console.log('[addElement] Nome do elemento:', elementName);

            if (!elementName) {
                alert('Por favor, informe o nome do elemento!');
                return;
            }

            var featureBaseName = featureName.replace(/\.feature$/i, '');
            fullElementKey = featureBaseName + '.' + elementName;

            htmlIdElement = document.getElementById("AutomationPR_PopUp_ElementId");
            CssSelectorElement = document.getElementById("AutomationPR_PopUp_CssSelector");
            XPathLocatorElement = document.getElementById("AutomationPR_PopUp_XPathLocator");

            var radios = document.getElementsByName('locatorType');
            selectedLocatorType = 'xpath';

            for (var i = 0; i < radios.length; i++) {
                if (radios[i].checked) {
                    selectedLocatorType = radios[i].value;
                    break;
                }
            }

            console.log('[addElement] Tipo de locator selecionado:', selectedLocatorType);

            switch (selectedLocatorType) {
                case 'id':
                    selectedLocatorValue = decodeHtml(htmlIdElement.getAttribute('data-value') || '');
                    break;
                case 'css':
                    selectedLocatorValue = decodeHtml(CssSelectorElement.getAttribute('data-value') || '');
                    break;
                case 'xpath':
                default:
                    selectedLocatorValue = decodeHtml(XPathLocatorElement.getAttribute('data-value') || '');
                    break;
            }

            console.log('[addElement] Valor do locator:', selectedLocatorValue);

            if (!selectedLocatorValue || selectedLocatorValue === '') {
                alert('O locator selecionado está vazio! Por favor, selecione outro tipo de locator.');
                return;
            }

            saveToLocalStorageImmediately(featureBaseName, elementName, selectedLocatorType, selectedLocatorValue);

            JsonData = {
                "Command": "AddElement",
                "Caller": "addElement",
                "CommandId": pseudoGuid(),
                "ElementCodeName": fullElementKey,
                "SelectedLocatorType": selectedLocatorType,
                "SelectedLocatorValue": selectedLocatorValue
            };

            createCommand(JsonData);

            var insertBtn = document.getElementById("AutomationPR_InsertButton");
            if (insertBtn) {
                insertBtn.style.display = 'inline-block';
                console.log('[SALVAR] Botão Inserir agora visível');
            }

            var saveBtn = document.getElementById("AutomationPR_SaveButton");
            var originalText = saveBtn.value;
            saveBtn.value = '✓ Adicionado';
            saveBtn.style.backgroundColor = '#28a745';
            saveBtn.style.color = 'white';

            codeIDTextElement.value = '';
            codeIDTextElement.focus();

            setTimeout(function () {
                saveBtn.value = originalText;
                saveBtn.style.backgroundColor = '';
                saveBtn.style.color = '';
            }, 1000);

            console.log('[addElement] Elemento adicionado à lista: ' + fullElementKey);

            return bye("addElement");
        };

        function saveToLocalStorageImmediately(featureName, elementName, locatorType, locatorValue) {
            console.log('[LOCAL STORAGE] Salvando:', featureName, elementName);

            var locatorData = {
                feature: featureName,
                element: elementName,
                locatorType: locatorType,
                locatorValue: locatorValue,
                timestamp: new Date().toISOString(),
                fullKey: featureName + '.' + elementName
            };

            var allLocators = JSON.parse(localStorage.getItem('automationLocators') || '[]');
            allLocators.push(locatorData);
            localStorage.setItem('automationLocators', JSON.stringify(allLocators));

            console.log('[LOCAL STORAGE] ✅ Salvo! Total:', allLocators.length);
            showNotification('Locator salvo! Total: ' + allLocators.length);
        }

        window.updateFeatures = function (features) {
            console.log('[UPDATE] Atualizando features:', features);
            window.availableFeatures = features;

            var dropdown = document.getElementById("AutomationPR_FeatureSelect");
            if (dropdown) {
                dropdown.innerHTML = '';

                var defaultOption = document.createElement('option');
                defaultOption.value = '';
                defaultOption.text = 'Selecione uma Feature...';
                dropdown.appendChild(defaultOption);

                if (features && Array.isArray(features) && features.length > 0) {
                    features.forEach(function (feature) {
                        var option = document.createElement('option');
                        option.value = feature;
                        option.text = feature;
                        dropdown.appendChild(option);
                    });
                }
            }
        };

        return Automation_Page_Recorder;

    })();

    addStyle(`
    @keyframes slideDown {
        from {
            opacity: 0;
            transform: translateX(-50%) translateY(-20px);
        }
        to {
            opacity: 1;
            transform: translateX(-50%) translateY(0);
        }
    }
    
    @keyframes slideUp {
        from {
            opacity: 1;
            transform: translateX(-50%) translateY(0);
        }
        to {
            opacity: 0;
            transform: translateX(-50%) translateY(-20px);
        }
    }
`);

    addStyle(`
    #locatorCounter button {
        transition: all 0.2s ease;
        font-family: Arial, sans-serif;
    }
    
    #locatorCounter button:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 8px rgba(0,0,0,0.2);
    }
    
    #locatorCounter button:active {
        transform: translateY(0);
    }
    
    .locator-notification {
        animation: slideIn 0.3s ease, fadeOut 0.5s ease 2.5s;
    }
    
    @keyframes slideIn {
        from { transform: translateX(100%); opacity: 0; }
        to { transform: translateX(0); opacity: 1; }
    }
    
    @keyframes fadeOut {
        from { opacity: 1; }
        to { opacity: 0; }
    }
`);

    addStyle(".highlight { background-color:silver !important}");
    addStyle("table#AutomationTable { background-color:Azure; border-collapse:collapse; } table#AutomationTable,table#AutomationTable th, table#AutomationTable td { font-family: Verdana, Arial; font-size: 10pt; padding-left:10pt; padding-right:10pt; border-bottom: 1px solid black; }");
    addStyle("input#AutomationPR_PopUp_CodeIDText { display:table-cell; width:95%; }");
    addStyle("#AutomationPR_FeatureSelect { font-family: Verdana, Arial; font-size: 10pt; padding: 5px; }");
    addStyle("span#AutomationPR_PopUp_CloseButton { display:table-cell; -moz-border-radius: 4px; -webkit-border-radius: 4px; -o-border-radius: 4px; border-radius: 4px; border: 1px solid #ccc; color: white; background-color: #980000; cursor: pointer; font-size: 10pt; padding: 0px 2px; font-weight: bold; position: absolute; right: 3px; top: 8px; }");
    addStyle("div#AutomationPR_PopUp { display:none; } div#AutomationPR_PopUp_Element_Name { display:table; width: 100%; }");

    if (document.body != null) {
        if (document.body.addEventListener) {
            document.body.addEventListener('mouseover', handler, true);
            document.addEventListener('contextmenu', rightClickHandler, true);
        } else if (document.body.attachEvent) {
            document.body.attachEvent('mouseover', function (e) {
                return handler(e || window.event);
            });
            document.body.attachEvent('oncontextmenu', function (e) {
                return rightClickHandler(e || window.event);
            });
        } else {
            document.body.onmouseover = handler;
            document.body.onmouseover = rightClickHandler;
        }
        document.Automation_Page_Recorder = new Automation_Page_Recorder();
        document.Automation_Page_Recorder.createElementForm();
    } else {
        say("Document has no body tag... Injecting empty Automation");
        document.Automation_Page_Recorder = "STUB. Document has no body tag :(";
    }

    // 🔹 VARIÁVEL GLOBAL PARA CACHE DO ARQUIVO
    let fileHandleCache = null;

    // 🔹 FUNÇÃO PRINCIPAL - DETECTA HTTP OU HTTPS
    window.handleSaveToXml = async function () {
        var allLocators = JSON.parse(localStorage.getItem('automationLocators') || '[]');

        if (allLocators.length === 0) {
            alert("Nenhum locator na lista para inserir no XML!");
            return;
        }

        // 🔹 VERIFICA SE TEM File System Access API (HTTPS)
        if (window.showOpenFilePicker) {
            await handleSaveViaFilePicker(allLocators);
        } else {
            // 🔹 FALLBACK: Salva em TXT (HTTP)
            await handleSaveViaInputFile(allLocators);
        }
    };

    // 🔹 MÉTODO 1: File Picker API (HTTPS - SALVA DIRETO NO XML)
    async function handleSaveViaFilePicker(allLocators) {
        try {
            if (!fileHandleCache) {
                console.log('[XML HTTPS] Solicitando arquivo...');
                [fileHandleCache] = await window.showOpenFilePicker({
                    types: [{ description: 'XML File', accept: { 'text/xml': ['.xml'] } }],
                    multiple: false,
                    startIn: 'desktop'
                });
            }

            if (await fileHandleCache.queryPermission({ mode: 'readwrite' }) !== 'granted') {
                await fileHandleCache.requestPermission({ mode: 'readwrite' });
            }

            const file = await fileHandleCache.getFile();
            const text = await file.text();
            const xmlDoc = new DOMParser().parseFromString(text, "text/xml");
            let root = xmlDoc.getElementsByTagName("locators")[0];

            if (!root) {
                alert("Erro: Tag <locators> não encontrada!");
                return;
            }

            let insertedCount = 0;
            allLocators.forEach(function (locator) {
                const newElement = xmlDoc.createElement("element");
                newElement.setAttribute("key", locator.feature + "." + locator.element);
                newElement.setAttribute("by", locator.locatorType);
                newElement.setAttribute("value", locator.locatorValue);
                newElement.setAttribute("baseValue", "");

                root.appendChild(xmlDoc.createTextNode("\n  "));
                root.appendChild(newElement);
                insertedCount++;
            });

            root.appendChild(xmlDoc.createTextNode("\n"));

            const serializer = new XMLSerializer();
            let xmlString = serializer.serializeToString(xmlDoc);
            xmlString = xmlString.replace(/<\?xml[^?]*\?>\s*/g, '');
            xmlString = xmlString.replace(/>\s*</g, '>\n<');

            const writable = await fileHandleCache.createWritable();
            await writable.write('<?xml version="1.0" encoding="utf-8"?>\n' + xmlString);
            await writable.close();

            console.log('[XML HTTPS] ✅ ' + insertedCount + ' locators inseridos');
            showNotification("✅ " + insertedCount + " locators inseridos!");

            localStorage.removeItem('automationLocators');
            document.getElementById("AutomationPR_InsertButton").style.display = 'none';

            alert("✅ " + insertedCount + " locators inseridos com sucesso!");

        } catch (err) {
            if (err.name !== 'AbortError') {
                fileHandleCache = null;
                console.error('[XML HTTPS] Erro:', err);
                alert("❌ Erro: " + err.message);
            }
        }
    }

    // 🔹 MÉTODO 2: Salvar em TXT (HTTP - SEM PICKER)
    async function handleSaveViaInputFile(allLocators) {
        // 🔹 MOSTRA AVISO HTTP
        showHttpWarning();

        try {
            // 🔹 CRIA CONTEÚDO TXT COM OS ELEMENTOS
            let txtContent = '';

            allLocators.forEach(function (locator) {
                const element = `<element key="${locator.feature}.${locator.element}" by="${locator.locatorType}" value="${locator.locatorValue}" baseValue="" />`;
                txtContent += element + '\n';
            });

            // 🔹 CRIA E BAIXA O ARQUIVO Object.txt
            const blob = new Blob([txtContent], { type: 'text/plain;charset=utf-8' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'Object.txt';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);

            console.log('[TXT HTTP] ✅ ' + allLocators.length + ' locators salvos em Object.txt');
            showNotification("✅ " + allLocators.length + " locators salvos em Object.txt!");

            // 🔹 LIMPA A LISTA E ESCONDE O BOTÃO
            localStorage.removeItem('automationLocators');
            document.getElementById("AutomationPR_InsertButton").style.display = 'none';

            alert(
                "✅ " + allLocators.length + " locators salvos!\n\n" +
                "📥 Arquivo 'Object.txt' foi baixado.\n" +
                "Copie os elementos e cole no PageObjects.xml."
            );

        } catch (err) {
            console.error('[TXT HTTP] Erro:', err);
            alert("❌ Erro ao salvar: " + err.message);
        }
    }

    // 🔹 FUNÇÃO: Mostra aviso para sites HTTP
    function showHttpWarning() {
        const existingWarning = document.getElementById('httpSecurityWarning');
        if (existingWarning) {
            existingWarning.remove();
        }

        const warning = document.createElement('div');
        warning.id = 'httpSecurityWarning';
        warning.innerHTML = `
        <div style="display: flex; align-items: flex-start; gap: 12px;">
            <div style="flex-shrink: 0; font-size: 24px;">⚠️</div>
            <div style="flex: 1;">
                <div style="font-weight: bold; font-size: 14px; margin-bottom: 8px;">
                    Site sem HTTPS detectado
                </div>
                <div style="font-size: 12px; line-height: 1.5; color: #333;">
                    Como este site usa <strong>HTTP</strong> (não seguro), o navegador não permite salvar arquivos diretamente.<br><br>
                    📥 <strong>O arquivo 'Object.txt' será baixado</strong> com os elementos.<br>
                    📋 Copie o conteúdo e <strong>cole no PageObjects.xml</strong> manualmente.
                </div>
            </div>
            <button id="closeHttpWarning" style="
                background: none;
                border: none;
                font-size: 20px;
                cursor: pointer;
                color: #666;
                padding: 0;
                width: 24px;
                height: 24px;
                display: flex;
                align-items: center;
                justify-content: center;
                flex-shrink: 0;
            ">✕</button>
        </div>
    `;

        warning.style.position = 'fixed';
        warning.style.top = '20px';
        warning.style.left = '50%';
        warning.style.transform = 'translateX(-50%)';
        warning.style.backgroundColor = '#FFF3CD';
        warning.style.border = '2px solid #FFC107';
        warning.style.borderRadius = '8px';
        warning.style.padding = '16px 20px';
        warning.style.boxShadow = '0 4px 12px rgba(0,0,0,0.15)';
        warning.style.zIndex = '9999999';
        warning.style.maxWidth = '500px';
        warning.style.width = '90%';
        warning.style.fontFamily = 'Arial, sans-serif';
        warning.style.animation = 'slideDown 0.3s ease';

        document.body.appendChild(warning);

        const closeBtn = document.getElementById('closeHttpWarning');
        closeBtn.onmouseover = function () { this.style.color = '#000'; };
        closeBtn.onmouseout = function () { this.style.color = '#666'; };
        closeBtn.onclick = function () {
            warning.style.animation = 'slideUp 0.3s ease';
            setTimeout(() => warning.remove(), 300);
        };

        setTimeout(function () {
            if (warning && warning.parentNode) {
                warning.style.animation = 'slideUp 0.3s ease';
                setTimeout(() => {
                    if (warning.parentNode) {
                        warning.remove();
                    }
                }, 300);
            }
        }, 7000);
    }

    function getSelectedLocator() {
        if (document.getElementById("chkId").checked)
            return { by: "id", value: document.getElementById("AutomationPR_PopUp_ElementId").getAttribute('data-value') };
        if (document.getElementById("chkXpath").checked)
            return { by: "xpath", value: document.getElementById("AutomationPR_PopUp_XPathLocator").getAttribute('data-value') };
        return { by: "css", value: document.getElementById("AutomationPR_PopUp_CssSelector").getAttribute('data-value') };
    }

}).call(this);